[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "swu_rec"
version = "5.0"
requires-python = ">=3.13"
dependencies = [
    "loguru             >= 0.7.3",
    "numpy              >= 2.2.6",
    "pandas             >= 2.0",
    "selenium           >= 4.41.0",
    "requests           >= 2.32.3",
    "webdriver-manager  >= 4.0.2",
    "GitPython          >= 3.1.60"
]

[tool.setuptools]
package-dir = { "" = "src" }

[project.scripts]
swu-rec = "swu_rec:main"
swu-rec_daily = "swu_rec_git:main"
